package com.dushop;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.dushop.common.entity.Customer;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.security
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-18  13:53
 *@Description: TODO
 *@Version: 1.0
 */

public class CustomerUserDetails implements UserDetails {
    private Customer customer;
    /*Auto-generated by InteliJ Idea*/
    public CustomerUserDetails(Customer customer) {
        this.customer = customer;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public String getPassword() {
        return customer.getPassword();
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public String getUsername() {
        return customer.getEmail();
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public boolean isEnabled() {
        return customer.isEnabled();
    }
    /*Auto-generated by InteliJ Idea*/
    public String getFullName() {
        return customer.getFirstName() + " " + customer.getLastName();
    }

    /*Auto-generated by InteliJ Idea*/
    public Customer getCustomer() {
        return this.customer;
    }
}