package com.dushop.admin;
/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.admin.order
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-30  09:42
 *@Description: TODO
 *@Version: 1.0
 */

public class ProductDTO {
    private String name;
    private String imagePath;
    private float price;
    private float cost;

    /*Auto-generated by InteliJ Idea*/
    public ProductDTO(String name, String imagePath, float price, float cost) {
        this.name = name;
        this.imagePath = imagePath;
        this.price = price;
        this.cost = cost;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getName() {
        return name;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setName(String name) {
        this.name = name;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getImagePath() {
        return imagePath;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    /*Auto-generated by InteliJ Idea*/
    public float getPrice() {
        return price;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setPrice(float price) {
        this.price = price;
    }
    /*Auto-generated by InteliJ Idea*/
    public float getCost() {
        return cost;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setCost(float cost) {
        this.cost = cost;
    }
}