package com.dushop.common.entity.order;

import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.persistence.Transient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.dushop.common.entity.IdBasedEntity;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity.order
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-29  19:50
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "order_track")
public class OrderTrack extends IdBasedEntity {

    /*self-finish*/
    @Column(length = 256)
    private String notes;

    /*self-finish*/
    private Date updatedTime;

    /*self-finish*/
    @Enumerated(EnumType.STRING)
    @Column(length = 45, nullable = false)
    private OrderStatus status;

    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;

 //////////////////////////////////////////////////////////////////////////////////
 /*Auto-generated by InteliJ Idea*/
    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Date getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }
    /*Auto-generated by InteliJ Idea*/
    /////////////////////////////////////////////////////////////////////////
    /***************************************************************************************
     *    Title: mediCare
     *    Author: Bhardwaj-Abh
     *    Availability: https://github.com/Bhardwaj-Abh/medi/blob/32f56a6712eec42f688d93b1de83de0efb96f702/MediCareCommon/src/main/java/com/medicare/common/entity/order/Order.java *
     ***************************************************************************************/
    /***************************************************************************************
     *    Title: mediCare
     *    Author: Bhardwaj-Abh
     *    Availability: https://github.com/Bhardwaj-Abh/medi/blob/32f56a6712eec42f688d93b1de83de0efb96f702/MediCareCommon/src/main/java/com/medicare/common/entity/order/Order.java *
     ***************************************************************************************/
    @Transient
    public String getUpdatedTimeOnForm() {
        DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ss");
        return dateFormatter.format(this.updatedTime);
    }

    /***************************************************************************************
     *    Title: mediCare
     *    Author: Bhardwaj-Abh
     *    Availability: https://github.com/Bhardwaj-Abh/medi/blob/32f56a6712eec42f688d93b1de83de0efb96f702/MediCareCommon/src/main/java/com/medicare/common/entity/order/Order.java *
     ***************************************************************************************/

    public void setUpdatedTimeOnForm(String dateString) {
        DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ss");

        try {
            this.updatedTime = dateFormatter.parse(dateString);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

}