package com.dushop.admin;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.dushop.common.entity.Role;
import com.dushop.common.entity.User;


/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.admin.security
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-07-22  19:16
 *@Description: TODO
 *@Version: 1.0
 */

public class DuShopUserDetails implements UserDetails {

    private User user;
    private static final long serialVersionUID = 1L;
    /*Auto-generated by InteliJ Idea*/
    public DuShopUserDetails(User user) {
        this.user = user;
    }

    /*Auto-generated by InteliJ Idea and partly adopted from
@Author: Code Java.
“Spring Boot Tutorials Playlist” [online]
 Available at: https://youtu.be/zDc63OHY_v8
*/
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        Set<Role> roles = user.getRoles();
        List<SimpleGrantedAuthority> authories = new ArrayList<>();
        for (Role role : roles) {
            authories.add(new SimpleGrantedAuthority(role.getName()));
        }
        return authories;
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    @Override
    public boolean isEnabled() {
        return user.isEnabled();
    }

    /*Auto-generated by InteliJ Idea, and modify by myself*/
   @Override
   public String getPassword() {
       return user.getPassword();
    }


    /*Auto-generated by InteliJ Idea, and modify by myself*/
    @Override
    public String getUsername() {
        return user.getEmail(); //There is get email
    }

    /*Auto-generated by InteliJ Idea, and modify by myself*/
    public void setFirstName(String firstName) {
        this.user.setFirstName(firstName);
    }

    /*self-code*/ /*Auto-generated by InteliJ Idea, and modify by myself*/
    public void setLastName(String lastName) {
        this.user.setLastName(lastName);
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    public boolean hasRole(String roleName) {
        return user.hasRole(roleName);
    }

    /*Auto-generated by InteliJ Idea, and modify by myself*/
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /*self-code*/
    public String getFullname() {
        return this.user.getFirstName() + " " + this.user.getLastName(); //get userName is get email
    }

    /*Auto-generated by InteliJ Idea, and modify by myself*/
}
