package com.dushop.admin;

import java.nio.file.Path;
import java.nio.file.Paths;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.method.support.HandlerMethodArgumentResolver;

import java.util.List;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.admin
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-07-13  13:11
 *@Description: TODO
 *@Version: 1.0
 */

@Configuration
public class MvcConfig implements WebMvcConfigurer {

/*Auto-generated by InteliJ Idea
   and partly adopted from
@Author: Code Java.
“Spring Boot Tutorials Playlist” [online]
 Available at: https://youtu.be/zDc63OHY_v8
*/
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        exposeDirectory("user-photos", registry);
        exposeDirectory("../category-images", registry);
        exposeDirectory("../brand-logos", registry);
        exposeDirectory("../product-images", registry);
        exposeDirectory("../site-logo", registry);
    }

    /*****************************
     @Author: Code Java.
     “Spring Boot Tutorials Playlist” [online]
     Available at: https://youtu.be/zDc63OHY_v8
     ****************************/
    private void exposeDirectory(String pathPattern, ResourceHandlerRegistry registry) {
        Path path = Paths.get(pathPattern);
        String absolutePath = path.toFile().getAbsolutePath();

        String logicalPath = pathPattern.replace("../", "") + "/**";

        registry.addResourceHandler(logicalPath)
                .addResourceLocations("file:/" + absolutePath + "/");
    }

    /*Auto-generated by InteliJ Idea
   and partly adopted from
@Author: Code Java.
“Spring Boot Tutorials Playlist” [online]
 Available at: https://youtu.be/zDc63OHY_v8
*/
    @Override
    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
        resolvers.add(new PagingAndSortingArgumentResolver());
    }
}
