package com.dushop.admin;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.admin.order
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-30  15:56
 *@Description: TODO
 *@Version: 1.0
 */

@RestController
public class OrderRestController {

    @Autowired
    private OrderService service;

    /***************************************************************************************
     *    Title: mediCare
     *    Author: Bhardwaj-Abh
     *    Availability: https://github.com/Bhardwaj-Abh/medi/blob/32f56a6712eec42f688d93b1de83de0efb96f702/MediCareCommon/src/main/java/com/medicare
     ***************************************************************************************/
    @PostMapping("/orders_shipper/update/{id}/{status}")
    public Response updateOrderStatus(@PathVariable("id") Integer orderId, @PathVariable("status") String status) {
        service.updateStatus(orderId, status);
        return new Response(orderId, status);
    }
}

/***************************************************************************************
 *    Title: mediCare
 *    Author: Bhardwaj-Abh
 *    Availability: https://github.com/Bhardwaj-Abh/medi/blob/32f56a6712eec42f688d93b1de83de0efb96f702/MediCareCommon/src/main/java/com/medicare
 ***************************************************************************************/
class Response {
    private Integer orderId;
    private String status;

    public Response(Integer orderId, String status) {
        this.orderId = orderId;
        this.status = status;
    }

    /*Auto-generated by InteliJ Idea, and modify by myself*/
    public Integer getOrderId() {
        return orderId;
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    public String getStatus() {
        return status;
    }
    /*Auto-generated by InteliJ Idea, and modify by myself*/
    public void setStatus(String status) {
        this.status = status;
    }

}