package com.dushop;

import java.util.Collection;
import java.util.Map;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.core.user.OAuth2User;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.oauth
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-23  21:13
 *@Description: TODO
 *@Version: 1.0
 */

public class CustomerOAuth2User implements OAuth2User {

    private String clientName;
    private OAuth2User oauth2User;

    private String fullName;

    /*Auto-generated by InteliJ Idea*/
    public CustomerOAuth2User(OAuth2User user, String clientName) {
        this.oauth2User = user;
        this.clientName = clientName;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getClientName() {
        return clientName;
    }

    /************************************
     @Author: Jay Gajera
     “Spring E commerce project | With Code| Run step by step execution” [online]
     Available at: https://youtu.be/c6WWdINWSlI
     ************************************/
    @Override
    public Map<String, Object> getAttributes() {
        return oauth2User.getAttributes();
    }

    /************************************
     @Author: Jay Gajera
     “Spring E commerce project | With Code| Run step by step execution” [online]
     Available at: https://youtu.be/c6WWdINWSlI
     ************************************/
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return oauth2User.getAuthorities();
    }

    /************************************
     @Author: Jay Gajera
     “Spring E commerce project | With Code| Run step by step execution” [online]
     Available at: https://youtu.be/c6WWdINWSlI
     ************************************/
    @Override
    public String getName() {
        return oauth2User.getAttribute("name");
    }

    /************************************
     @Author: Jay Gajera
     “Spring E commerce project | With Code| Run step by step execution” [online]
     Available at: https://youtu.be/c6WWdINWSlI
     ************************************/
    public String getEmail() {
        return oauth2User.getAttribute("email");
    }

    /************************************
     @Author: Jay Gajera
     “Spring E commerce project | With Code| Run step by step execution” [online]
     Available at: https://youtu.be/c6WWdINWSlI
     ************************************/
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /************************************
     @Author: Jay Gajera
     “Spring E commerce project | With Code| Run step by step execution” [online]
     Available at: https://youtu.be/c6WWdINWSlI
     ************************************/
    public String getFullName() {
        return fullName != null ? fullName : oauth2User.getAttribute("name");
    }
}