package com.dushop;
/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.order
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-30  20:46
 *@Description: TODO
 *@Version: 1.0
 */

public class OrderReturnRequest {
    private Integer orderId;
    private String reason;
    private String note;

    /*Auto-generated by InteliJ Idea*/
    public OrderReturnRequest() {
    }
    /*Auto-generated by InteliJ Idea*/
    public OrderReturnRequest(Integer orderId, String reason, String note) {
        this.orderId = orderId;
        this.reason = reason;
        this.note = note;
    }
    /*Auto-generated by InteliJ Idea*/
    public Integer getOrderId() {
        return orderId;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getReason() {
        return reason;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setReason(String reason) {
        this.reason = reason;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getNote() {
        return note;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setNote(String note) {
        this.note = note;
    }
}