package com.dushop;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.order
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-30  20:46
 *@Description: TODO
 *@Version: 1.0
 */

public class OrderReturnResponse {
    private Integer orderId;
    /*Auto-generated by InteliJ Idea*/
    public OrderReturnResponse() { }

    /************************************
     @Author:  Learn Programming with Real Apps
     “Completed E-Commerce with Spring MVC and Spring Data JPA Playlist” [online]
     Available at: https://youtu.be/hwSB50DqMkc
     ************************************/
    public OrderReturnResponse(Integer orderId) {
        this.orderId = orderId;
    }
    /*Auto-generated by InteliJ Idea*/
    public Integer getOrderId() {
        return orderId;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}