package com.dushop.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-27  15:17
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "addresses")
public class Address extends AbstractAddressWithCountry{

    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;


    /*self-finish*/
    @Column(name = "default_address")
    private boolean defaultForShipping;

    /////////////////////////////////////////
    /*Auto-generated by InteliJ Idea*/
    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public boolean isDefaultForShipping() {
        return defaultForShipping;
    }

    public void setDefaultForShipping(boolean defaultForShipping) {
        this.defaultForShipping = defaultForShipping;
    }
    /*Auto-generated by InteliJ Idea*/
    /////////////////////////////////////////////


}
