package com.dushop.common.entity;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-24  21:50
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "cart_items")
public class CartItem extends IdBasedEntity {

    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;

    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;

    /*self-finish*/
    private int quantity;

    /*self-finish*/
    @Transient
    private float shippingCost;

    /*Auto-generated by InteliJ Idea*/
    public CartItem() {
    }

    /*Auto-generated by InteliJ Idea*/
    public Customer getCustomer() {
        return customer;
    }

    /*Auto-generated by InteliJ Idea*/
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    /*Auto-generated by InteliJ Idea*/
    public Product getProduct() {
        return product;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setProduct(Product product) {
        this.product = product;
    }
    /*Auto-generated by InteliJ Idea*/
    public int getQuantity() {
        return quantity;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public String toString() {
        return "CartItem [id=" + id + ", customer=" + customer.getFullName() + ", product=" + product.getShortName() + ", quantity=" + quantity
                + "]";
    }

    /*Auto-generated by InteliJ Idea*/
    public void setShippingCost(float shippingCost) {
        this.shippingCost = shippingCost;
    }


    /*self-finish*/
    @Transient
    public float getSubtotal() {
        return product.getDiscountPrice() * quantity;
    }


    /*Auto-generated by InteliJ Idea*/
    @Transient
    public float getShippingCost() {
        return shippingCost;
    }

}