package com.dushop.common.entity;

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;


/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-07-24  12:50
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "categories")
public class Category extends IdBasedEntity {


    /*self-finish*/
    @Column(length = 128, nullable = false, unique = true)
    private String name;

    /*self-finish*/
    @Column(length = 64, nullable = false, unique = true)
    private String alias;

    /*self-finish*/
    @Column(length = 128, nullable = false)
    private String image;

    /*self-finish*/
    private boolean enabled;

    /*self-finish*/
    @Column(name = "all_parent_ids", length = 256, nullable = true)
    private String allParentIDs;

    /*self-finish*/
    @OneToOne
    @JoinColumn(name = "parent_id")
    private Category parent;

    /*self-finish*/
    @OneToMany(mappedBy = "parent")
    @OrderBy("name asc")
    private Set<Category> children = new HashSet<>();

    /*Auto-generated by InteliJ Idea*/
    public Category() {
    }
    /*Auto-generated by InteliJ Idea*/
    public Category(Integer id) {
        this.id = id;
    }

    /*self-finish*/
    public static Category copyIdAndName(Category category) {
        //set the category to the subcategory set -->CategoryService--listCategoriesUsedInForm
        Category copyCategory = new Category();
        copyCategory.setId(category.getId());
        copyCategory.setName(category.getName());
        copyCategory.setHasChildren(category.getChildren().size() > 0);

        return copyCategory;
    }

    /*self-finish*/
    public static Category copyIdAndName(Integer id, String name) {
        Category copyCategory = new Category();
        copyCategory.setId(id);
        copyCategory.setName(name);

        return copyCategory;
    }


    /*self-finish*/
    public static Category copyFull(Category category) {
        Category copyCategory = new Category();
        copyCategory.setId(category.getId());
        copyCategory.setName(category.getName());
        copyCategory.setImage(category.getImage());
        copyCategory.setAlias(category.getAlias());
        copyCategory.setEnabled(category.isEnabled());
        copyCategory.setHasChildren(category.getChildren().size() > 0);

        return copyCategory;
    }

    /*self-finish*/

    public static Category copyFull(Category category, String name) {
        Category copyCategory = Category.copyFull(category);
        copyCategory.setName(name);

        return copyCategory;
    }

    //Bug-fixed: Property or field 'imagePath' cannot be found on object of type 'com.dushop.common.entity.Category'
    // - maybe not public or not valid?
    /*
@Author: Code Java.
“Spring Boot Tutorials Playlist” [online]
Available at: https://youtu.be/zDc63OHY_v8
*/
    @Transient
    public String getImagePath() {
        if (this.id == null)
            return "/images/image-thumbnail.png";
        return "/category-images/" + this.id + "/" + this.image;
    }

    /*Auto-generated by InteliJ Idea*/
    public Category(String name) {
        this.name = name;
        this.alias = name;
        this.image = "default.png";
    }
    /*Auto-generated by InteliJ Idea*/
    public Category(String name, Category parent) {
        this(name);
        this.parent = parent;
    }
    /*Auto-generated by InteliJ Idea*/
    public Category(Integer id, String name, String alias) {
        super();
        this.id = id;
        this.name = name;
        this.alias = alias;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getName() {
        return name;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setName(String name) {
        this.name = name;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getAlias() {
        return alias;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setAlias(String alias) {
        this.alias = alias;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getImage() {
        return image;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setImage(String image) {
        this.image = image;
    }
    /*Auto-generated by InteliJ Idea*/
    public boolean isEnabled() {
        return enabled;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    /*Auto-generated by InteliJ Idea*/
    public Category getParent() {
        return parent;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setParent(Category parent) {
        this.parent = parent;
    }
    /*Auto-generated by InteliJ Idea*/
    public Set<Category> getChildren() {
        return children;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setChildren(Set<Category> children) {
        this.children = children;
    }

    /*self-finish*/
    public boolean isHasChildren() {
        return hasChildren;
    }

    /*Auto-generated by InteliJ Idea*/
    public void setHasChildren(boolean hasChildren) {
        this.hasChildren = hasChildren;
    }

    /*self-finish*/
    @Transient
    private boolean hasChildren;

    /*self-finish*/
    @Override
    public String toString() {
        return this.name;
    }

    /*
    @Author: Code Java.
    “Spring Boot Tutorials Playlist” [online]
    Available at: https://youtu.be/zDc63OHY_v8
    */
    public String getAllParentIDs() {
        return allParentIDs;
    }

    /*
@Author: Code Java.
“Spring Boot Tutorials Playlist” [online]
Available at: https://youtu.be/zDc63OHY_v8
*/
    public void setAllParentIDs(String allParentIDs) {
        this.allParentIDs = allParentIDs;
    }
}