package com.dushop.common.entity;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/*
 *@sql author Sagun Khosla <sagunxp@gmail.com>
 *@github: https://github.com/sagunkho/geo-sql-database/blob/master/geo_countries.sql
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-14  10:58
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "countries")
public class Country extends IdBasedEntity {
    /*self-finish*/
    @Column(nullable = false, length = 45)
    private String name;
    /*self-finish*/
    @Column(nullable = false, length = 5)
    private String code;
    /*self-finish*/
    @OneToMany(mappedBy = "country")
    private Set<State> states;

/*Auto-generated by InteliJ Idea*/
    public Country() {

    }

    /*Auto-generated by InteliJ Idea*/
    public Country(Integer id) {
        this.id = id;
    }

    /*Auto-generated by InteliJ Idea*/
    public Country(String name) {
        this.name = name;
    }

    /*Auto-generated by InteliJ Idea*/
    public Country(String name, String code) {
        this.name = name;
        this.code = code;
    }

    /*Auto-generated by InteliJ Idea*/
    public Country(Integer id, String name, String code) {
        this.id = id;
        this.name = name;
        this.code = code;
    }

    /*Auto-generated by InteliJ Idea*/
    public String getName() {
        return name;
    }

    /*Auto-generated by InteliJ Idea*/
    public void setName(String name) {
        this.name = name;
    }

    /*Auto-generated by InteliJ Idea*/
    public String getCode() {
        return code;
    }

    /*Auto-generated by InteliJ Idea*/
    public void setCode(String code) {
        this.code = code;
    }

    /*Auto-generated by InteliJ Idea*/
    @Override
    public String toString() {
        return "Country [id=" + id + ", name=" + name + ", code=" + code + "]";
    }

}