package com.dushop.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-06  19:49
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "product_images")
public class ProductImage extends IdBasedEntity {
    /*self-finish*/
    @Column(nullable = false)
    private String name;

    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;

    ////////////////////////////////////////////////////////////
    /*Auto-generated by InteliJ Idea*/

    public ProductImage() {
    }

    public ProductImage(Integer id, String name, Product product) {
        this.id = id;
        this.name = name;
        this.product = product;
    }


    public ProductImage(String name, Product product) {
        this.name = name;
        this.product = product;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    /*Auto-generated by InteliJ Idea*/
    ///////////////////////////////////////////////////////////////////////

    /*
    @Author: Code Java.
    “Spring Boot Tutorials Playlist” [online]
    Available at: https://youtu.be/zDc63OHY_v8
*/
    @Transient
    public String getImagePath() {
        return "/product-images/" + product.getId() + "/extras/" + this.name;
    }

}