package com.dushop.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-07  23:47
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "product_details")
public class ProductDetail extends IdBasedEntity {

    /*self-finish*/
    @Column(nullable = false, length = 255)
    private String name;

    /*self-finish*/
    @Column(nullable = false, length = 255)
    private String value;

    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;

////////////////////////////////////////////////////
/*Auto-generated by InteliJ Idea*/
    public ProductDetail() {
    }

    public ProductDetail(Integer id, String name, String value, Product product) {
        super();
        this.id = id;
        this.name = name;
        this.value = value;
        this.product = product;
    }



    public ProductDetail(String name, String value, Product product) {
        this.name = name;
        this.value = value;
        this.product = product;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
    /*Auto-generated by InteliJ Idea*/
    ////////////////////////////////////
}