package com.dushop.common.entity;

import javax.persistence.*;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-13  19:16
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "settings")
public class Setting {

    /*self-finish*/
    @Id
    @Column(name = "`key`", nullable = false, length = 5000)
    private String key;

    /*self-finish*/
    @Column(nullable = false, length = 5000)
    private String value;

    /*self-finish*/
    @Enumerated(EnumType.STRING)
    @Column(length = 45, nullable = false)
    private SettingCategory category;


    /////////////////////////////////////////////////////////////////
    /*Auto-generated by InteliJ Idea*/
    public Setting() {

    }

    public Setting(String key, String value, SettingCategory category) {
        this.key = key;
        this.value = value;
        this.category = category;
    }

    public Setting(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public SettingCategory getCategory() {
        return category;
    }

    public void setCategory(SettingCategory category) {
        this.category = category;
    }

    /*Auto-generated by InteliJ Idea*/
    /////////////////////////////////////////

    /*self-finish*/
    @Override
    public int hashCode() {
        final int prime = 17;
        int result = 1;
        result = prime * result + ((key == null) ? 0 : key.hashCode());
        return result;
    }


    /*Auto-generated by InteliJ Idea*/
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Setting other = (Setting) obj;
        if (key == null) {
            if (other.key != null)
                return false;
        } else if (!key.equals(other.key))
            return false;
        return true;
    }


    /*Auto-generated by InteliJ Idea*/
    @Override
    public String toString() {
        return "Setting [key=" + key + ", value=" + value + "]";
    }

}
