package com.dushop.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-25  17:35
 *@Description: TODO
 *@Version: 1.0
 */

@Entity
@Table(name = "shipping_rates")
public class ShippingRate extends IdBasedEntity {
    /*self-finish*/
    private float rate;
    /*self-finish*/
    private int days;
    /*self-finish*/
    @Column(name = "cod_supported")
    private boolean codSupported;
    /*self-finish*/
    @ManyToOne
    @JoinColumn(name = "country_id")
    private Country country;
    /*self-finish*/
    @Column(nullable = false, length = 45)
    private String state;
    /*Auto-generated by InteliJ Idea*/
    public float getRate() {
        return rate;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setRate(float rate) {
        this.rate = rate;
    }
    /*Auto-generated by InteliJ Idea*/
    public int getDays() {
        return days;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setDays(int days) {
        this.days = days;
    }
    /*Auto-generated by InteliJ Idea*/
    public boolean isCodSupported() {
        return codSupported;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setCodSupported(boolean codSupported) {
        this.codSupported = codSupported;
    }
    /*Auto-generated by InteliJ Idea*/
    public Country getCountry() {
        return country;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setCountry(Country country) {
        this.country = country;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getState() {
        return state;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setState(String state) {
        this.state = state;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public String toString() {
        return "ShippingRate [id=" + id + ", rate=" + rate + ", days=" + days + ", codSupported=" + codSupported
                + ", country=" + country.getName() + ", state=" + state + "]";
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ShippingRate other = (ShippingRate) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }


}