package com.dushop.common.entity;
/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.admin.setting.state
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-08-15  14:40
 *@Description: TODO
 *@Version: 1.0
 */

public class StateDTO {
    /*self-finish*/
    private Integer id;
    /*self-finish*/
    private String name;
    /*Auto-generated by InteliJ Idea*/
    public StateDTO() {

    }
    /*Auto-generated by InteliJ Idea*/
    public StateDTO(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
    /*Auto-generated by InteliJ Idea*/
    public Integer getId() {
        return id;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setId(Integer id) {
        this.id = id;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getName() {
        return name;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setName(String name) {
        this.name = name;
    }
}
