package com.dushop.common.entity;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.Iterator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
/*
 *@BelongsProject: DuShopProject
 *@BelongsPackage: com.dushop.common.entity
 *@Author: Jiang Chufeng
 *@CreateTime: 2022-07-10  13:32
 *@Description: Backend Admin User Entity.
 *   Set the dushopdb-user attributes. The joint table user_roles is created here.
 *@Version: 1.0
 */

@Entity
@Table(name = "users")
public class User extends IdBasedEntity {
    /*self-finish*/
    @Column(length = 128, nullable = false, unique = true)
    private String email;
    /*self-finish*/
    @Column(length = 64, nullable = false)
    private String password;
    /*self-finish*/
    @Column(name = "first_name", length = 45, nullable = false)
    private String firstName;
    /*self-finish*/
    @Column(name = "last_name", length = 45, nullable = false)
    private String lastName;
    /*self-finish*/
    @Column(length = 64)
    private String photos;
    /*self-finish*/
    private boolean enabled;
    /*self-finish*/
    @ManyToMany(fetch = FetchType.EAGER) //FetchType.EAGER:立刻加载,在加载主体对象时,同时加载关联属性对象
    @JoinTable(
            name = "users_roles",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )

    /*self-finish*/
    private Set<Role> roles = new HashSet<>();
    /*Auto-generated by InteliJ Idea*/
    public User() {
    }
    /*Auto-generated by InteliJ Idea*/
    public User(String email, String password, String firstName, String lastName) {
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getEmail() {
        return email;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setEmail(String email) {
        this.email = email;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getPassword() {
        return password;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setPassword(String password) {
        this.password = password;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getFirstName() {
        return firstName;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getLastName() {
        return lastName;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    /*Auto-generated by InteliJ Idea*/
    public String getPhotos() {
        return photos;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setPhotos(String photos) {
        this.photos = photos;
    }
    /*Auto-generated by InteliJ Idea*/
    public boolean isEnabled() {
        return enabled;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    /*Auto-generated by InteliJ Idea*/
    public Set<Role> getRoles() {
        return roles;
    }
    /*Auto-generated by InteliJ Idea*/
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
    /*Auto-generated by InteliJ Idea*/
    public void addRole(Role role) {
        this.roles.add(role);
    }
    /*Auto-generated by InteliJ Idea*/
    @Override
    public String toString() {
        return "User [id=" + id + ", email=" + email + ", firstName=" + firstName + ", lastName=" + lastName
                + ", roles=" + roles + "]";
    }
    /*****************************
     @Author: Code Java.
     “Spring Boot Tutorials Playlist” [online]
     Available at: https://youtu.be/zDc63OHY_v8
     ****************************/
    @Transient
    public String getPhotosImagePath() {
        if (id == null || photos == null) return "/images/default-user.png";

        return "/user-photos/" + this.id + "/" + this.photos;
    }
    /*Auto-generated by InteliJ Idea*/
    @Transient
    public String getFullName() {
        return firstName + " " + lastName;
    }

    /*self-finish*/
    public boolean hasRole(String roleName) {
        Iterator<Role> iterator = roles.iterator();
        while (iterator.hasNext()) {
            Role role = iterator.next();
            if (role.getName().equals(roleName)) {
                return true;
            }
        }
        return false;
    }

}

